spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hl7db2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate     # ❗ usually 'validate' in prod
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
