name: Java CI Build

on:
  push:
    branches:
      - main  # Trigger only when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project with Maven
        run: mvn clean package -DskipTests
