name: Java CI Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project with Maven
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image for ${{ matrix.env }}
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/extravars:${{ matrix.env }} .

      - name: Push Docker image for ${{ matrix.env }}
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/extravars:${{ matrix.env }}
